##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Combinatorics.PermutationsTest+DomainSpec']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Combinatorics.PermutationsTest+DomainSpec ¯ <Default>']
##teamcity[testFailed name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Combinatorics.PermutationsTest+DomainSpec ¯ <Default> ¯ Object = Object, A = 1, B = 3' message='AssertionException' details='Operations:|r|nV   <Reset_Instance_Fields>|r|nV   <Arrangement>|r|nV   <Arrangement>|r|nV   <Action>|r|n ?  returns result (AssertionException)|r|n|r|n|r|nNUnit.Framework.AssertionException:|r|nExpected 5, but found 4.|r|n   at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message) in z:\Builds\work\b7ceef20fdfcf0ee\Shared\Execution\LateBoundTestFramework.cs:line 30|r|n   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in z:\Builds\work\b7ceef20fdfcf0ee\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 42|r|n   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in z:\Builds\work\b7ceef20fdfcf0ee\FluentAssertions.Core\Execution\DefaultAssertionStrategy.cs:line 25|r|n   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[|] args) in z:\Builds\work\b7ceef20fdfcf0ee\FluentAssertions.Core\Execution\AssertionScope.cs:line 197|r|n   at FluentAssertions.Numeric.NumericAssertions`1.Be(T expected, String because, Object[|] reasonArgs) in z:\Builds\work\b7ceef20fdfcf0ee\FluentAssertions.Core\Numeric\NumericAssertions.cs:line 44|r|n']
##teamcity[testFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Combinatorics.PermutationsTest+DomainSpec ¯ <Default> ¯ Object = Object, A = 1, B = 4' duration='xx']
##teamcity[testFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Combinatorics.PermutationsTest+DomainSpec ¯ <Default> ¯ Object = Object, A = 2, B = 3' duration='xx']
##teamcity[testFailed name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Combinatorics.PermutationsTest+DomainSpec ¯ <Default> ¯ Object = Object, A = 2, B = 4' message='AssertionException' details='Operations:|r|nV   <Reset_Instance_Fields>|r|nV   <Arrangement>|r|nV   <Arrangement>|r|nV   <Action>|r|n ?  returns result (AssertionException)|r|n|r|n|r|nNUnit.Framework.AssertionException:|r|nExpected 5, but found 6.|r|n   at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message) in z:\Builds\work\b7ceef20fdfcf0ee\Shared\Execution\LateBoundTestFramework.cs:line 30|r|n   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in z:\Builds\work\b7ceef20fdfcf0ee\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 42|r|n   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in z:\Builds\work\b7ceef20fdfcf0ee\FluentAssertions.Core\Execution\DefaultAssertionStrategy.cs:line 25|r|n   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[|] args) in z:\Builds\work\b7ceef20fdfcf0ee\FluentAssertions.Core\Execution\AssertionScope.cs:line 197|r|n   at FluentAssertions.Numeric.NumericAssertions`1.Be(T expected, String because, Object[|] reasonArgs) in z:\Builds\work\b7ceef20fdfcf0ee\FluentAssertions.Core\Numeric\NumericAssertions.cs:line 44|r|n']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Combinatorics.PermutationsTest+DomainSpec ¯ <Default>']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Combinatorics.PermutationsTest+DomainSpec']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Combinatorics.SequencesTest+DomainSpec']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Combinatorics.SequencesTest+DomainSpec ¯ <Default>']
##teamcity[testFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Combinatorics.SequencesTest+DomainSpec ¯ <Default> ¯ First sequence' duration='xx']
##teamcity[testFailed name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Combinatorics.SequencesTest+DomainSpec ¯ <Default> ¯ Second sequence' message='AssertionException' details='Operations:|r|nV   <Reset_Instance_Fields>|r|nV   <Arrangement>|r|nV   <Arrangement>|r|nV   <Action>|r|n ?  returns result (AssertionException)|r|n|r|n|r|nNUnit.Framework.AssertionException:|r|nExpected 6, but found 5.|r|n   at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message) in z:\Builds\work\b7ceef20fdfcf0ee\Shared\Execution\LateBoundTestFramework.cs:line 30|r|n   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in z:\Builds\work\b7ceef20fdfcf0ee\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 42|r|n   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in z:\Builds\work\b7ceef20fdfcf0ee\FluentAssertions.Core\Execution\DefaultAssertionStrategy.cs:line 25|r|n   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[|] args) in z:\Builds\work\b7ceef20fdfcf0ee\FluentAssertions.Core\Execution\AssertionScope.cs:line 197|r|n   at FluentAssertions.Numeric.NumericAssertions`1.Be(T expected, String because, Object[|] reasonArgs) in z:\Builds\work\b7ceef20fdfcf0ee\FluentAssertions.Core\Numeric\NumericAssertions.cs:line 44|r|n']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Combinatorics.SequencesTest+DomainSpec ¯ <Default>']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Combinatorics.SequencesTest+DomainSpec']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.ContextBehaviorTest+DomainSpec']
##teamcity[testFailed name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.ContextBehaviorTest+DomainSpec ¯ <Default>' message='AssertionException' details='Operations:|r|nV   subject with ctor arg|r|nV   <Action>|r|nV   has result set to ctor arg|r|n ?  has property set to null (AssertionException)|r|n|r|n|r|nNUnit.Framework.AssertionException:|r|nExpected string to be <null>, but found "ctor arg".|r|n   at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message) in z:\Builds\work\b7ceef20fdfcf0ee\Shared\Execution\LateBoundTestFramework.cs:line 30|r|n   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in z:\Builds\work\b7ceef20fdfcf0ee\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 42|r|n   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in z:\Builds\work\b7ceef20fdfcf0ee\FluentAssertions.Core\Execution\DefaultAssertionStrategy.cs:line 25|r|n   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[|] args) in z:\Builds\work\b7ceef20fdfcf0ee\FluentAssertions.Core\Execution\AssertionScope.cs:line 197|r|n   at FluentAssertions.Primitives.ReferenceTypeAssertions`2.BeNull(String because, Object[|] reasonArgs) in z:\Builds\work\b7ceef20fdfcf0ee\FluentAssertions.Core\Primitives\ReferenceTypeAssertions.cs:line 33|r|n']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.ContextBehaviorTest+DomainSpec']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Exceptions.UnexpectedExceptionTest+DomainSpec']
##teamcity[testFailed name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Exceptions.UnexpectedExceptionTest+DomainSpec ¯ <Default>' message='ArgumentException' details='Operations:|r|nV   <Reset_Instance_Fields>|r|nV   a message|r|nV   an inner exception with message|r|n ?  <Action> (ArgumentException)|r|n|r|n|r|nSystem.ArgumentException:|r|nMessage|r|n---> InnerMessage|r|n   at UserNamespace.UserClass.Throw[TException|](String message, Exception innerException) in c:\TestFx\src\TestFx.SpecK.Tests\Exceptions\UserClass.cs:line 26|r|n|r|n--- Begin of inner exception stack trace ---|r|n|r|n']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Exceptions.UnexpectedExceptionTest+DomainSpec']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Exceptions.ExceptionAssertionTest+DomainSpec']
##teamcity[testFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Exceptions.ExceptionAssertionTest+DomainSpec ¯ <Default>' duration='xx']
##teamcity[testFailed name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Exceptions.ExceptionAssertionTest+DomainSpec ¯ Wrong exception type' message='Exception' details='Operations:|r|nV   <Reset_Instance_Fields>|r|nV   <Action>|r|n ?  Throws InvalidOperationException (Exception)|r|n|r|n|r|nSystem.Exception:|r|nException must be assignable to |'System.InvalidOperationException|' but was |'ArgumentNullException|'.|r|n']
##teamcity[testFailed name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Exceptions.ExceptionAssertionTest+DomainSpec ¯ Wrong message' message='Exception' details='Operations:|r|nV   <Reset_Instance_Fields>|r|nV   <Action>|r|n ?  Throws ArgumentException (Exception)|r|n|r|n|r|nSystem.Exception:|r|nException message must be |'Wrong message|' but was |'[NullGuard|] message is null.|r|nParameter name: message|'.|r|n']
##teamcity[testFailed name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Exceptions.ExceptionAssertionTest+DomainSpec ¯ Wrong message provider' message='Exception' details='Operations:|r|nV   <Reset_Instance_Fields>|r|nV   a message|r|nV   <Action>|r|n ?  Throws ArgumentException (Exception)|r|n|r|n|r|nSystem.Exception:|r|nException message must be |'Wrong message|' but was |'[NullGuard|] innerException is null.|r|nParameter name: innerException|'.|r|n']
##teamcity[testFailed name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Exceptions.ExceptionAssertionTest+DomainSpec ¯ Wrong inner exception provider' message='Exception' details='Operations:|r|nV   <Reset_Instance_Fields>|r|nV   a message|r|nV   <Action>|r|n ?  Throws ArgumentException (Exception)|r|n|r|n|r|nSystem.Exception:|r|nException message must be |'Message|' but was |'[NullGuard|] innerException is null.|r|nParameter name: innerException|'.|r|n']
##teamcity[testFailed name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Exceptions.ExceptionAssertionTest+DomainSpec ¯ Custom failing assertion' message='AssertionException' details='Operations:|r|nV   <Reset_Instance_Fields>|r|nV   <Action>|r|n ?  Throws exception with special properties (AssertionException)|r|n|r|n|r|nNUnit.Framework.AssertionException:|r|nExpected object not to be <null>.|r|n   at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message) in z:\Builds\work\b7ceef20fdfcf0ee\Shared\Execution\LateBoundTestFramework.cs:line 30|r|n   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in z:\Builds\work\b7ceef20fdfcf0ee\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 42|r|n   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in z:\Builds\work\b7ceef20fdfcf0ee\FluentAssertions.Core\Execution\DefaultAssertionStrategy.cs:line 25|r|n   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[|] args) in z:\Builds\work\b7ceef20fdfcf0ee\FluentAssertions.Core\Execution\AssertionScope.cs:line 197|r|n   at FluentAssertions.Primitives.ReferenceTypeAssertions`2.NotBeNull(String because, Object[|] reasonArgs) in z:\Builds\work\b7ceef20fdfcf0ee\FluentAssertions.Core\Primitives\ReferenceTypeAssertions.cs:line 53|r|n']
##teamcity[testFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Exceptions.ExceptionAssertionTest+DomainSpec ¯ Custom passing assertion' duration='xx']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Exceptions.ExceptionAssertionTest+DomainSpec']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Farada.AutoCreationTest+DomainSpec']
##teamcity[testFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Farada.AutoCreationTest+DomainSpec ¯ <Default>' duration='xx']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Farada.AutoCreationTest+DomainSpec']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Setups.SimpleSetupExecutionTest+DomainSpec']
##teamcity[testFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Setups.SimpleSetupExecutionTest+DomainSpec ¯ <Default>' duration='xx']
##teamcity[testFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Setups.SimpleSetupExecutionTest+DomainSpec ¯ Case 2' duration='xx']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Setups.SimpleSetupExecutionTest+DomainSpec']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Setups.ThrowingSetupExecutionTest+DomainSpec']
##teamcity[testFailed name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Setups.ThrowingSetupExecutionTest+DomainSpec' message='Exception' details='Operations:|r|nV   SetupOnceMethod|r|n ?  <.cctor>b__0 (Exception)|r|n.. InnerOperations ..|r|nV   CleanupOnceMethod|r|n']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Setups.ThrowingSetupExecutionTest+DomainSpec']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Simple.IsolationTest+DomainSpec']
##teamcity[testFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Simple.IsolationTest+DomainSpec ¯ Setting' duration='xx']
##teamcity[testFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Simple.IsolationTest+DomainSpec ¯ Reusing' duration='xx']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Simple.IsolationTest+DomainSpec']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Simple.VariableTest+DomainSpec']
##teamcity[testFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Simple.VariableTest+DomainSpec ¯ <Default>' duration='xx']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Simple.VariableTest+DomainSpec']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.FakeItEasy.OrderedAssertionsTest+DomainSpec']
##teamcity[testFailed name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.FakeItEasy.OrderedAssertionsTest+DomainSpec ¯ <Default>' message='ExpectationException' details='Operations:|r|nV   <Reset_Instance_Fields>|r|nV   <Create_Fakes>|r|nV   <Create_Subject>|r|nV   <Action>|r|n ?  calls in order first and second disposable (ExpectationException)|r|n|r|n|r|nFakeItEasy.ExpectationException:|r|n|r|n|r|n  Assertion failed for the following calls:|r|n    |'System.IDisposable.Dispose()|' repeated at least once|r|n    |'System.IDisposable.Dispose()|' repeated at least once|r|n  The calls where found but not in the correct order among the calls:|r|n    1: System.IDisposable.Dispose()|r|n    2: System.IDisposable.Dispose()|r|n|r|n   at FakeItEasy.Core.OrderedFakeAsserter.ThrowExceptionWhenAssertionFailed(List`1 assertedCalls, CallWriter callWriter, IEnumerable`1 originalCallList)|r|n   at FakeItEasy.Core.OrderedFakeAsserter.AssertWasCalled(Func`2 callPredicate, String callDescription, Func`2 repeatPredicate, String repeatDescription)|r|n   at FakeItEasy.Core.OrderedFakeAsserterFactory.CompositeAsserter.AssertWasCalled(Func`2 callPredicate, String callDescription, Func`2 repeatPredicate, String repeatDescription)|r|n   at FakeItEasy.Configuration.RuleBuilder.MustHaveHappened(Repeated repeatConstraint)|r|n   at FakeItEasy.AssertConfigurationExtensions.MustHaveHappened(IAssertConfiguration configuration)|r|n']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.FakeItEasy.OrderedAssertionsTest+DomainSpec']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.FakeItEasy.FakeSetupTest+DomainSpec']
##teamcity[testFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.FakeItEasy.FakeSetupTest+DomainSpec ¯ <Default>' duration='xx']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.FakeItEasy.FakeSetupTest+DomainSpec']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.FakeItEasy.FakeCreationTest+DomainSpec']
##teamcity[testFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.FakeItEasy.FakeCreationTest+DomainSpec ¯ <Default>' duration='xx']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.FakeItEasy.FakeCreationTest+DomainSpec']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Subject.CustomCreationTest+DomainSpec']
##teamcity[testFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Subject.CustomCreationTest+DomainSpec ¯ <Default>' duration='xx']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Subject.CustomCreationTest+DomainSpec']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Subject.AdHocCreationTest+DomainSpec']
##teamcity[testFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Subject.AdHocCreationTest+DomainSpec ¯ <Default>' duration='xx']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Subject.AdHocCreationTest+DomainSpec']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Using.FailingTest+DomainSpec']
##teamcity[testFailed name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Using.FailingTest+DomainSpec ¯ <Default>' message='TargetInvocationException' details='Operations:|r|nV   Create PassingDisposable|r|n ?  Create ThrowingDisposable (TargetInvocationException)|r|nV   Dispose PassingDisposable|r|n|r|n|r|nSystem.Reflection.TargetInvocationException:|r|nException has been thrown by the target of an invocation.|r|n---> Exception of type |'System.Exception|' was thrown.|r|n   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)|r|n   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)|r|n   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)|r|n   at System.Activator.CreateInstance(Type type, Boolean nonPublic)|r|n   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[|] args, CultureInfo culture, Object[|] activationAttributes, StackCrawlMark& stackMark)|r|n   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[|] args, CultureInfo culture, Object[|] activationAttributes)|r|n   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[|] args, CultureInfo culture)|r|n|r|n--- Begin of inner exception stack trace ---|r|n']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Using.FailingTest+DomainSpec']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Using.NestingTest+DomainSpec']
##teamcity[testFailed name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Using.NestingTest+DomainSpec ¯ <Default>' message='Exception' details='Operations:|r|nV   Create FirstDisposable|r|nV   Create SecondDisposable (named)|r|nV   Create DelegateDisposable|r|nV   Arrangement|r|nV   Create ThirdDisposable|r|nV   <Action>|r|n ?  Failing Assertion (Exception)|r|nV   Dispose ThirdDisposable|r|nV   Dispose DelegateDisposable|r|nV   Dispose SecondDisposable (named)|r|nV   Dispose FirstDisposable|r|n|r|n|r|nSystem.Exception:|r|nException of type |'System.Exception|' was thrown.|r|n']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Using.NestingTest+DomainSpec']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Subject.NoDefaultConstructorTest+DomainSpec']
##teamcity[testFailed name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Subject.NoDefaultConstructorTest+DomainSpec ¯ <Default>' message='EvaluationException' details='Operations:|r|n ?  <Create_Subject> (EvaluationException)|r|n|r|n|r|nTestFx.Evaluation.EvaluationException:|r|nMissing default constructor for subject type |'DomainType|'.|r|n']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Subject.NoDefaultConstructorTest+DomainSpec']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Subject.MissingArgumentsTest+DomainSpec']
##teamcity[testFailed name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Subject.MissingArgumentsTest+DomainSpec ¯ <Default>' message='EvaluationException' details='Operations:|r|n ?  <Create_Subject> (EvaluationException)|r|n|r|n|r|nTestFx.Evaluation.EvaluationException:|r|nMissing constructor arguments for subject type |'DomainType|': firstMissingString, secondMissingString|r|n']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Subject.MissingArgumentsTest+DomainSpec']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Subject.DefaultCreationTest+DomainSpec']
##teamcity[testFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Subject.DefaultCreationTest+DomainSpec ¯ <Default>' duration='xx']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Subject.DefaultCreationTest+DomainSpec']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Simple.FailingTest+DomainSpec']
##teamcity[testFailed name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Simple.FailingTest+DomainSpec ¯ <Default>' message='2 Exceptions' details='Operations:|r|nV   <Action>|r|n ?  Failing assertion (Exception)|r|nV   Passing assertion|r|n ?  Another failing assertion (Exception)|r|n|r|n|r|nSystem.Exception:|r|nException of type |'System.Exception|' was thrown.|r|n|r|n|r|nSystem.Exception:|r|nException of type |'System.Exception|' was thrown.|r|n']
##teamcity[testFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Simple.FailingTest+DomainSpec ¯ Passing' duration='xx']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Simple.FailingTest+DomainSpec']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Simple.HaltingTest+DomainSpec']
##teamcity[testFailed name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Simple.HaltingTest+DomainSpec ¯ <Default>' message='Exception' details='Operations:|r|n ?  Throwing arrangement (Exception)|r|n|r|n|r|nSystem.Exception:|r|nException of type |'System.Exception|' was thrown.|r|n']
##teamcity[testFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Simple.HaltingTest+DomainSpec ¯ Passing' duration='xx']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Simple.HaltingTest+DomainSpec']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Simple.PassingTest+DomainSpec']
##teamcity[testFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Simple.PassingTest+DomainSpec ¯ <Default>' duration='xx']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll ¯ TestFx.SpecK.Tests.Simple.PassingTest+DomainSpec']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.SpecK.Tests.dll']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.MSpec.Tests.dll']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.MSpec.Tests.dll ¯ TestFx.MSpec.Tests.when_calling']
##teamcity[testFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.MSpec.Tests.dll ¯ TestFx.MSpec.Tests.when_calling ¯ asserts' duration='xx']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.MSpec.Tests.dll ¯ TestFx.MSpec.Tests.when_calling']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.MSpec.Tests.dll ¯ TestFx.MSpec.Tests.outer_context+when_actioning']
##teamcity[testFailed name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.MSpec.Tests.dll ¯ TestFx.MSpec.Tests.outer_context+when_actioning' message='TargetInvocationException' details='Operations:|r|n ?  Establish outer_context_base (TargetInvocationException)|r|n.. InnerOperations ..|r|n']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.MSpec.Tests.dll ¯ TestFx.MSpec.Tests.outer_context+when_actioning']
##teamcity[testSuiteStarted name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.MSpec.Tests.dll ¯ TestFx.MSpec.Tests.when_adding']
##teamcity[testFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.MSpec.Tests.dll ¯ TestFx.MSpec.Tests.when_adding ¯ returns_three' duration='xx']
##teamcity[testFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.MSpec.Tests.dll ¯ TestFx.MSpec.Tests.when_adding ¯ returns_three_again' duration='xx']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.MSpec.Tests.dll ¯ TestFx.MSpec.Tests.when_adding']
##teamcity[testSuiteFinished name='C:\TestFx\src\TestFx.Console.Tests\bin\Debug\TestFx.MSpec.Tests.dll']
